version: '3.8'

services:
  audio-merger:
    build: .
    image: audio-merger:latest
    container_name: audio-merger
    ports:
      - "8080:5000"
    restart: unless-stopped
    environment:
      - PORT=5000
    # Production-ready settings
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - audio-network

networks:
  audio-network:
    driver: bridge
